config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :team_members, only: [:index, :create, :update, :destroy]
  resources :jobseekers, only: [:index, :new, :create, :update, :destroy]
  resources :projects, only: [:index, :create, :edit, :update, :destroy]
  resources :trades, only: [:index, :create, :destroy]
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobseeker.rb
class Jobseeker < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_trade_and_last_name_and_address_line3_and_post_code,
    against: [ :trade, :last_name, :address_line3, :post_code ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :location, presence: true
  has_one_attached :photo
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_one_attached :photo
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :jobseeker
  has_many :team_members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/jobseekers_controller.rb
class JobseekersController < ApplicationController
  def index
    if params[:query].present?
      @jobseekers = policy_scope(Jobseeker).search_by_trade_and_last_name_and_address_line3_and_post_code(params[:query])
    else
      @jobseekers = policy_scope(Jobseeker).order(created_at: :desc)
    end
  end

  def new
    @user = current_user
    if @user.jobseeker.present?
      @jobseeker = Jobseeker.find(@user.jobseeker.id)
    else
      @jobseeker = Jobseeker.new
    end
    authorize @jobseeker
  end

  def create
    @jobseeker = Jobseeker.new(jobseeker_params)
    @jobseeker.user = current_user
    authorize @jobseeker

    respond_to do |format|
      if @jobseeker.save
        JobseekerMailer.with(jobseeker: @jobseeker).register_jobseeker.deliver_now
        format.html { redirect_to(new_jobseeker_path, notice: "Jobseeker was sucessfully created.") }
        format.json { render json: @jobseeker, status: :created, location: @jobseeker }
      else
        format.html { render action: 'new' }
        format.json { render json: @jobseeker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    @jobseeker = Jobseeker.find(@user.jobseeker.id)
    authorize @jobseeker
    if @jobseeker.update(jobseeker_params)
      redirect_to new_jobseeker_path
    else
      render "jobseekers/new"
    end
  end

  def destroy
    @jobseeker = Jobseeker.find(params[:id])
    @jobseeker.destroy
  end

  def jobseeker_params
    params.require(:jobseeker).permit(:first_name, :last_name, :address_line1, :address_line2, :address_line3, :post_code, :phone_number, :email, :trade, :qualifications, :references, :enquiry)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @projects = policy_scope(Project).order(created_at: :desc)
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    if @project.save
      redirect_to projects_path
    else
      render "index"
    end
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    if @project.update(project_params)
      direct_to projects_path
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :location, :description, :photo)
  end
end

app/controllers/team_member_controller.rb
class TeamMemberController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @team_members = TeamMember.all
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    if @team_member.save
      redirect_to team_members_path
    else
      render "index"
  end

  def update
    @team_member = TeamMember.find(params[:id])
    @team_member.update(team_member_params)
  end

  def destroy
    @team_member = TeamMember.find(params[:id])
    @team_member.destroy
  end

  def team_member_params
    params.require(:team_member).permit[:first_name, :last_name, :position, :info]
  end

end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @team_members = policy_scope(TeamMember).order(created_at: :asc)
    @team_member = TeamMember.new
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    if @team_member.save
      redirect_to team_members_path
    else
      render "index"
    end
  end

  def update
    @team_member = TeamMember.find(params[:id])
    @team_member.update(team_member_params)
  end

  def destroy
    @team_member = TeamMember.find(params[:id])
    @team_member.destroy
  end

  def team_member_params
    params.require(:team_member).permit(:first_name, :last_name, :position, :info, :user_id, :photo)
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @trades = policy_scope(Trade).order(created_at: :desc)
    @trade = Trade.new
  end

  def create
    @trade = Trade.new(trade_params)
    authorize @trade
    if @trade.save
      redirect_to trades_path
    else
      render "index"
    end
  end

  def destroy
    @trade = Trade.find(params[:id])
    authorize @trade
    @trade.destroy
  end

  def trade_params
    params.require(:trade).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobseekers/index.html.erb
<h2 class="text-heading">Green star jobseekers</h2>

<div class="search-bar">
  <%= form_tag jobseekers_path, method: :get do %>
    <div class="input-field-jobseekers">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a jobseeker"
      %>
    </div>
    <%= submit_tag "Search", class: "btn btn-green-star btn-search" %>
  <% end %>

</div>

<table>
  <tr>
    <th>Full name</th>
    <th>Phone number</th>
    <th>Email</th>
    <th>Address line 1</th>
    <th>Address line 2</th>
    <th>Address line 3</th>
    <th>Postcode</th>
    <th>Trade</th>
    <th>Qualifications</th>
    <th>References</th>
    <th>Enquiry</th>
  </tr>
  <% @jobseekers.each do |joobseeker| %>
    <tr>
      <td><%= joobseeker.first_name %> <%= joobseeker.last_name %></td>
      <td><%= joobseeker.phone_number %></td>
      <td><%= joobseeker.email %></td>
      <td><%= joobseeker.address_line1 %></td>
      <td><%= joobseeker.address_line2 %></td>
      <td><%= joobseeker.address_line3 %></td>
      <td><%= joobseeker.post_code %></td>
      <td><%= joobseeker.trade %></td>
      <td><%= joobseeker.qualifications %></td>
      <td><%= joobseeker.references %></td>
      <td><%= joobseeker.enquiry %></td>
    </tr>
  <% end %>
</table>

app/views/jobseekers/new.html.erb
<% if policy(@jobseeker).create? %>
  <div class="form-green-star">
    <h3>Jobseeker form</h3>
    <hr/>
    <%= simple_form_for [@jobseeker] do |f| %>
      <%= f.input :first_name %>
      <hr/>
      <%= f.input :last_name %>
      <hr/>
      <%= f.input :address_line1 %>
      <hr/>
      <%= f.input :address_line2 %>
      <hr/>
      <%= f.input :address_line3 %>
      <hr/>
      <%= f.input :post_code %>
      <hr/>
      <%= f.input :phone_number %>
      <hr/>
      <%= f.input :email %>
      <hr/>
      <%= f.input :trade %>
      <hr/>
      <%= f.input :qualifications %>
      <hr/>
      <%= f.input :references %>
      <hr/>
      <%= f.input :enquiry %>
      <hr/>
      <%= f.submit "Submit", class: "btn-green-star" %>
    <% end %>
  </div>
<% end %>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenStar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="/assets/Green Star Rec Logo.jpg" rel="shortcut icon" type="image/jpg" />
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
  <footer id="footer">
    <%= render 'shared/footer' %>
  </footer>
</html>

app/views/pages/home.html.erb
<div id="company-name">
  <h1 id="text-name">Green star</h1>
  <p class="text-ordinary">Recruitment LtD</p>
</div>

<div class="line-home">
  <p class="text-description-home">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure quia aperiam consequatur ad quisquam facilis expedita cupiditate sed non fugiat est molestias doloribus, ipsum repellat suscipit sapiente nemo eius ipsa. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum officiis aliquid neque animi nostrum qui mollitia soluta dolor quam. Atque, eligendi. Culpa necessitatibus eveniet veniam sit vel, hic blanditiis ex?</p>
  <div class="star-home">
    <i class="fas fa-star"></i>
  </div>
</div>


<div class="icons-home">
  <%= image_tag "Tool box.png", alt: "Box", width: 200 %>
  <%= image_tag "House.png", alt: "House", width: 200 %>
  <%= image_tag "Paint can.png", alt: "Can", width: 200 %>
</div>

app/views/projects/edit.html.erb
  <div class="form-green-star">
    <h3>Edit project form</h3>
    <hr/>
    <%= simple_form_for [@project] do |f| %>
      <%= f.input :name %>
      <hr/>
      <%= f.input :location %>
      <hr/>
      <%= f.input :description %>
      <hr/>
      <%= f.input :photo, as: :file %>
      <hr/>
      <%= f.submit "Edit", class: "btn-green-star" %>
    <% end %>
  </div>

app/views/projects/index.html.erb
<div class="banner-project" style="background-image: linear-gradient(rgba(255,255,255,0.64), rgba(255,255,255,0.64)), url('<%= image_path "Track.png", alt: "Track" %>')">
  <div>
    <h2>Recent projects</h2>
    <p>we have supplied on:</p>
  </div>
</div>
<div class="grid-project">
  <% @projects.each do |project| %>
    <div class="card-project">
      <%if project.photo.present? %>
        <%= cl_image_tag project.photo.key, height: 400, width: 600, crop: :fill %>
      <% end %>
      <% if current_user.present? %>
        <div class="icons-projects">
          <% if policy(Project).destroy? %>
            <%= link_to project_path(project), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
          <% if policy(Project).update? %>
            <%= link_to edit_project_path(project) do %>
              <i class="far fa-edit"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <h4><%= project.name %></h4>
      <h6><%= project.location %></h6>
      <p><%= project.description %></p>
    </div>
  <% end %>

</div>

<% if current_user.present? %>
  <% if policy(Project).create? %>
    <div class="form-green-star">
      <h3>Project form</h3>
      <hr/>
      <%= simple_form_for [@project] do |f| %>
        <%= f.input :name %>
        <hr/>
        <%= f.input :location %>
        <hr/>
        <%= f.input :description %>
        <hr/>
        <%= f.input :photo, as: :file %>
        <hr/>
        <%= f.submit "Submit", class: "btn-green-star" %>
      <% end %>
    </div>
  <% end %>
<% end %>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="contact-footer">
    <h4>Contact us:</h4>
    <div class="icons-contact">
      <i class="fas fa-phone"></i>
      <h6>0203 405 4944</h6>
    </div>
    <div class="icons-contact">
      <i class="fas fa-mobile-alt"></i>
      <h6>07747 624 722</h6>
    </div>
    <div class="icons-contact">
      <i class="fas fa-envelope-open-text"></i>
      <h6>charles@greenstarrecruitment.co.uk</h6>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= image_tag "Green Star Rec Logo.jpg", alt: "logo", width: 80 %>
  <i><%= link_to "", root_path, class: "fas fa-home" %></i>
  <%= link_to "Projects", projects_path, class: "link-navbar" %>
  <%= link_to "Trades", trades_path, class: "link-navbar" %>
  <%= link_to "Our team", team_members_path, class: "link-navbar" %>
  <% if policy(Jobseeker).create? %>
    <%= link_to "For Jobseekers", new_jobseeker_path, class: "link-navbar" %>
  <% end %>
  <% if current_user.present? %>
    <% if current_user.email == "charles@greenstarrecruitment.co.uk" || current_user.email == "milo@greenstarrecruitment.co.uk" %>
      <%= link_to "Jobseekers", jobseekers_path %>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  <% end %>
</div>

app/views/team_members/index.html.erb
<h2 class="text-team-members">Our team:</h2>
<div class="grid-team">

  <% @team_members.each do |team_member| %>
    <div class="card-team">
      <%= cl_image_tag team_member.photo.key, height: 600, width: 400, crop: :fill %>
      <h4><%= team_member.first_name %> <%= team_member.last_name %></h4>
      <h6><%= team_member.position %></h6>
      <p><%= team_member.info %></p>
    </div>
  <% end %>


</div>

<% if current_user.present? %>
  <% if policy(TeamMember).create? %>
    <div class="form-green-star">
      <h3>Team member form</h3>
      <hr/>
      <%= simple_form_for [@team_member] do |f| %>
        <%= f.input :first_name %>
        <hr/>
        <%= f.input :last_name %>
        <hr/>
        <%= f.input :position %>
        <hr/>
        <%= f.input :info %>
        <hr/>
        <%= f.input :photo, as: :file %>
        <hr/>
        <%= f.submit "Submit", class: "btn-green-star" %>
      <% end %>
    </div>
  <% end %>
<% end %>
<br>
<br>

app/views/trades/index.html.erb
<div class="container-trades">
  <div class="col-trades">
    <h2>Some operatives</h2>
    <p>we supply</p>
    <% @trades.each do |trade| %>
      <div class="name-trades">
        <h3><%= trade.name %></h3>
        <% if current_user.present? %>
          <% if policy(Project).destroy? %>
            <%= link_to trade_path(trade), method: :delete do%>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>

  </div>
  <div class="col-trades-photos">
    <div class="fraction-trades">
      <%= image_tag "Bricklayer.png", alt: "Bricklayer", width: 510 %>
    </div>
    <div class="fraction-trades">
      <%= image_tag "Dryliners.jpg", alt: "Dryliners", width: 400 %>
    </div>
    <div class="fraction-trades">
      <%= image_tag "Groundworkers.jpg", alt: "Groundworkers", width: 510 %>
    </div>
    <div class="fraction-trades">
      <%= image_tag "Plasteres.jpg", alt: "Plasteres", width: 400 %>
    </div>
    <div class="fraction-trades">
      <%= image_tag "telescopic-forklift.jpg", alt: "telescopic-forklift", width: 450 %>
    </div>
    <div class="fraction-trades">
      <%= image_tag "Labourer.jpg", alt: "Labourer", width: 400 %>
    </div>
  </div>

</div>

<% if current_user.present? %>
  <% if policy(Trade).create? %>
    <div class="form-green-star">
      <h3>Trade form</h3>
      <hr/>
      <%= simple_form_for [@trade] do |f| %>
        <%= f.input :name %>
        <hr/>
        <%= f.submit "Submit", class: "btn-green-star" %>
      <% end %>
    </div>
  <% end %>
<% end %>
<br>
<br>